# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('agent_email', models.EmailField(max_length=254, null=True)),
                ('current_address', models.TextField()),
                ('property_address', models.TextField()),
            ],
        ),
    ]
