# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebuyer',
            name='housecanary',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
